/********************************************************************************
** Form generated from reading UI file 'siviso.ui'
**
** Created by: Qt User Interface Compiler version 5.6.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SIVISO_H
#define UI_SIVISO_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDial>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_siviso
{
public:
    QWidget *centralWidget;
    QFrame *Alertas;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *Alert;
    QFrame *BarraHerramientas;
    QFrame *ControlRec;
    QPushButton *rec;
    QPushButton *play;
    QFrame *ControlVolumen;
    QPushButton *vol_dw;
    QPushButton *vol_up;
    QLabel *label_19;
    QFrame *PulsoActivo;
    QPushButton *cw;
    QSpinBox *frecP;
    QSpinBox *nP;
    QSpinBox *anchoP;
    QDoubleSpinBox *ran_det;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QSpinBox *edo_mar;
    QLabel *label_21;
    QSpinBox *prob_deteccion;
    QLabel *label_23;
    QLabel *label_24;
    QSpinBox *escala_ppi;
    QLabel *label_26;
    QDial *dial;
    QGroupBox *ControlEmisor;
    QRadioButton *origenManual;
    QRadioButton *origenAuto;
    QRadioButton *origenOmni;
    QPushButton *startCom;
    QPushButton *lf;
    QPushButton *btr;
    QPushButton *ppi;
    QSpinBox *gan_sen;
    QPushButton *ppi_2;
    QPushButton *demon;
    QLabel *label_66;
    QFrame *frame;
    QPushButton *chirpUp;
    QPushButton *chirpDw;
    QPushButton *chype;
    QLabel *label_68;
    QSpinBox *chirpFrecUp;
    QLabel *label_73;
    QSpinBox *chirpFrecDw;
    QLabel *label_74;
    QLabel *label_75;
    QDoubleSpinBox *chirpTime;
    QSpinBox *water_vel;
    QLabel *label_77;
    QDoubleSpinBox *Ud;
    QLabel *label_70;
    QDoubleSpinBox *Uu;
    QPushButton *cleanP;
    QCheckBox *prefilter;
    QPushButton *cleanA;
    QCheckBox *windowing;
    QLabel *label_78;
    QSpinBox *central_frec;
    QLabel *label_79;
    QDoubleSpinBox *factor_p;
    QLabel *label_72;
    QSpinBox *dTotal;
    QLabel *label_76;
    QSpinBox *dPaso;
    QLabel *label_71;
    QSpinBox *limProm;
    QPushButton *sensor0;
    QPushButton *sensor1;
    QPushButton *autoSend;
    QFrame *Logos;
    QLabel *label_27;
    QLabel *label_9;
    QLabel *label_10;
    QFrame *PlataformaP;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_35;
    QLabel *B0Nom;
    QLabel *B0Time;
    QLabel *B0Lat;
    QLabel *B0Long;
    QLabel *B0Pr;
    QLabel *B0Temp;
    QLabel *B0Or;
    QLabel *B0Carg;
    QLabel *B0Volt;
    QLabel *B0estado;
    QLabel *label_34;
    QLabel *label_69;
    QLabel *B0Hu;
    QFrame *CompGraf;
    QSlider *setColorDw;
    QSlider *setColorUp;
    QFrame *despGraf;
    QPlainTextEdit *view;
    QPlainTextEdit *textTestGrap;
    QLineEdit *textSend;
    QPushButton *clean;
    QToolButton *toolButton;
    QDoubleSpinBox *prob_falsa;
    QPushButton *endCom;
    QPushButton *btOpenPort;
    QPushButton *GPSOr;
    QPushButton *ApagarP;
    QDoubleSpinBox *radio_boya;
    QPushButton *infoSignal;
    QPushButton *openJars;
    QPushButton *dataSim;
    QPushButton *closeJars;
    QLabel *label_58;
    QPushButton *ApagarA;
    QPushButton *save;
    QPushButton *dist;
    QPushButton *prog;
    QPushButton *pulso;
    QLabel *label_22;
    QDoubleSpinBox *dt;
    QLabel *label_8;
    QLabel *label_11;
    QLabel *label_12;
    QDoubleSpinBox *bw;
    QDoubleSpinBox *it;
    QDoubleSpinBox *escala_desp;
    QLabel *label_25;
    QPushButton *tipo_norte;
    QLabel *label_18;
    QGroupBox *ControlOrigen;
    QRadioButton *origenBlanco;
    QRadioButton *origenSensor;
    QRadioButton *origenBuque;
    QSpinBox *ang;
    QFrame *MedioAmbiente;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_54;
    QLabel *label_55;
    QLabel *label_56;
    QLabel *label_57;
    QLabel *dirV;
    QLabel *velV;
    QFrame *PlataformaActiva;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_51;
    QLabel *label_59;
    QLabel *label_60;
    QLabel *label_61;
    QLabel *label_62;
    QLabel *label_63;
    QLabel *label_64;
    QLabel *label_65;
    QLabel *B1Time_2;
    QLabel *B1Lat_2;
    QLabel *B1Temp;
    QLabel *B1Temp_2;
    QLabel *B1Volt_2;
    QLabel *B1Carg;
    QLabel *B1Nom;
    QLabel *B1Or;
    QLabel *B1Volt;
    QLabel *B1Lat;
    QLabel *B1Pr;
    QLabel *B1Long;
    QLabel *B1Time;
    QLabel *B1estado;
    QLabel *label_67;
    QLabel *B1Hu;
    QFrame *Blancos;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_47;
    QLabel *label_48;
    QFrame *frame_2;
    QLabel *label_90;
    QLabel *label_91;
    QLabel *label_92;
    QLabel *label_93;
    QLabel *label_94;
    QLabel *label_95;
    QLabel *label_96;
    QLabel *label_97;
    QLabel *label_98;
    QLabel *ori;
    QLabel *lat;
    QLabel *log;
    QLabel *profundidad;
    QLabel *label_99;
    QLabel *vel;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *siviso)
    {
        if (siviso->objectName().isEmpty())
            siviso->setObjectName(QStringLiteral("siviso"));
        siviso->resize(1920, 1080);
        centralWidget = new QWidget(siviso);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        Alertas = new QFrame(centralWidget);
        Alertas->setObjectName(QStringLiteral("Alertas"));
        Alertas->setGeometry(QRect(10, 9, 1281, 71));
        Alertas->setFrameShape(QFrame::StyledPanel);
        Alertas->setFrameShadow(QFrame::Raised);
        label = new QLabel(Alertas);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 10, 67, 17));
        QFont font;
        font.setPointSize(8);
        font.setBold(false);
        font.setItalic(false);
        font.setWeight(50);
        label->setFont(font);
        label_2 = new QLabel(Alertas);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 40, 67, 17));
        label_2->setFont(font);
        label_2->setTextFormat(Qt::AutoText);
        label_3 = new QLabel(Alertas);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(150, 40, 111, 17));
        label_3->setFont(font);
        label_4 = new QLabel(Alertas);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(450, 40, 171, 17));
        label_4->setFont(font);
        label_5 = new QLabel(Alertas);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(750, 40, 201, 17));
        label_5->setFont(font);
        label_6 = new QLabel(Alertas);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(1030, 40, 191, 17));
        label_6->setFont(font);
        Alert = new QLabel(Alertas);
        Alert->setObjectName(QStringLiteral("Alert"));
        Alert->setGeometry(QRect(60, 10, 981, 21));
        BarraHerramientas = new QFrame(centralWidget);
        BarraHerramientas->setObjectName(QStringLiteral("BarraHerramientas"));
        BarraHerramientas->setGeometry(QRect(9, 89, 1591, 211));
        BarraHerramientas->setFrameShape(QFrame::StyledPanel);
        BarraHerramientas->setFrameShadow(QFrame::Raised);
        ControlRec = new QFrame(BarraHerramientas);
        ControlRec->setObjectName(QStringLiteral("ControlRec"));
        ControlRec->setGeometry(QRect(10, 119, 71, 81));
        ControlRec->setFrameShape(QFrame::StyledPanel);
        ControlRec->setFrameShadow(QFrame::Raised);
        rec = new QPushButton(ControlRec);
        rec->setObjectName(QStringLiteral("rec"));
        rec->setGeometry(QRect(10, 10, 51, 27));
        QFont font1;
        font1.setPointSize(9);
        rec->setFont(font1);
        play = new QPushButton(ControlRec);
        play->setObjectName(QStringLiteral("play"));
        play->setGeometry(QRect(10, 43, 51, 27));
        QFont font2;
        font2.setPointSize(6);
        play->setFont(font2);
        ControlVolumen = new QFrame(BarraHerramientas);
        ControlVolumen->setObjectName(QStringLiteral("ControlVolumen"));
        ControlVolumen->setGeometry(QRect(90, 120, 111, 81));
        ControlVolumen->setFrameShape(QFrame::StyledPanel);
        ControlVolumen->setFrameShadow(QFrame::Raised);
        vol_dw = new QPushButton(ControlVolumen);
        vol_dw->setObjectName(QStringLiteral("vol_dw"));
        vol_dw->setGeometry(QRect(10, 30, 41, 27));
        vol_up = new QPushButton(ControlVolumen);
        vol_up->setObjectName(QStringLiteral("vol_up"));
        vol_up->setGeometry(QRect(60, 30, 41, 27));
        label_19 = new QLabel(ControlVolumen);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(30, 10, 67, 17));
        QFont font3;
        font3.setPointSize(8);
        font3.setBold(false);
        font3.setWeight(50);
        label_19->setFont(font3);
        PulsoActivo = new QFrame(BarraHerramientas);
        PulsoActivo->setObjectName(QStringLiteral("PulsoActivo"));
        PulsoActivo->setGeometry(QRect(580, 10, 491, 91));
        PulsoActivo->setFrameShape(QFrame::StyledPanel);
        PulsoActivo->setFrameShadow(QFrame::Raised);
        cw = new QPushButton(PulsoActivo);
        cw->setObjectName(QStringLiteral("cw"));
        cw->setGeometry(QRect(10, 40, 71, 41));
        frecP = new QSpinBox(PulsoActivo);
        frecP->setObjectName(QStringLiteral("frecP"));
        frecP->setGeometry(QRect(90, 40, 91, 41));
        frecP->setMinimum(2000);
        frecP->setMaximum(15000);
        frecP->setSingleStep(100);
        frecP->setValue(2000);
        nP = new QSpinBox(PulsoActivo);
        nP->setObjectName(QStringLiteral("nP"));
        nP->setGeometry(QRect(190, 40, 91, 41));
        nP->setMinimum(1);
        nP->setMaximum(65536);
        nP->setSingleStep(1000);
        nP->setValue(1000);
        anchoP = new QSpinBox(PulsoActivo);
        anchoP->setObjectName(QStringLiteral("anchoP"));
        anchoP->setGeometry(QRect(290, 40, 91, 41));
        anchoP->setMinimum(40);
        anchoP->setMaximum(50);
        anchoP->setValue(50);
        ran_det = new QDoubleSpinBox(PulsoActivo);
        ran_det->setObjectName(QStringLiteral("ran_det"));
        ran_det->setGeometry(QRect(390, 40, 91, 41));
        label_13 = new QLabel(PulsoActivo);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(30, 9, 51, 31));
        QFont font4;
        font4.setPointSize(10);
        font4.setBold(true);
        font4.setItalic(false);
        font4.setWeight(75);
        font4.setKerning(false);
        label_13->setFont(font4);
        label_13->setLayoutDirection(Qt::RightToLeft);
        label_13->setAutoFillBackground(false);
        label_13->setTextFormat(Qt::PlainText);
        label_13->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_14 = new QLabel(PulsoActivo);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(90, 20, 91, 20));
        label_14->setFont(font);
        label_14->setAlignment(Qt::AlignCenter);
        label_15 = new QLabel(PulsoActivo);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(190, 20, 91, 17));
        label_15->setFont(font);
        label_15->setAlignment(Qt::AlignCenter);
        label_16 = new QLabel(PulsoActivo);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(290, 20, 91, 17));
        label_16->setFont(font);
        label_16->setAlignment(Qt::AlignCenter);
        label_17 = new QLabel(PulsoActivo);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(390, 10, 91, 31));
        label_17->setFont(font);
        edo_mar = new QSpinBox(BarraHerramientas);
        edo_mar->setObjectName(QStringLiteral("edo_mar"));
        edo_mar->setGeometry(QRect(220, 160, 48, 41));
        label_21 = new QLabel(BarraHerramientas);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(210, 130, 67, 31));
        prob_deteccion = new QSpinBox(BarraHerramientas);
        prob_deteccion->setObjectName(QStringLiteral("prob_deteccion"));
        prob_deteccion->setGeometry(QRect(290, 160, 69, 41));
        prob_deteccion->setMinimum(0);
        prob_deteccion->setMaximum(99);
        prob_deteccion->setValue(50);
        label_23 = new QLabel(BarraHerramientas);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(276, 120, 91, 41));
        label_24 = new QLabel(BarraHerramientas);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(356, 120, 91, 41));
        escala_ppi = new QSpinBox(BarraHerramientas);
        escala_ppi->setObjectName(QStringLiteral("escala_ppi"));
        escala_ppi->setGeometry(QRect(370, 160, 69, 41));
        escala_ppi->setMinimum(1);
        escala_ppi->setMaximum(1000);
        label_26 = new QLabel(BarraHerramientas);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(540, 136, 81, 21));
        dial = new QDial(BarraHerramientas);
        dial->setObjectName(QStringLiteral("dial"));
        dial->setGeometry(QRect(1410, 0, 181, 211));
        dial->setMinimum(-179);
        dial->setMaximum(180);
        dial->setOrientation(Qt::Horizontal);
        ControlEmisor = new QGroupBox(BarraHerramientas);
        ControlEmisor->setObjectName(QStringLiteral("ControlEmisor"));
        ControlEmisor->setGeometry(QRect(1290, 10, 120, 101));
        origenManual = new QRadioButton(ControlEmisor);
        origenManual->setObjectName(QStringLiteral("origenManual"));
        origenManual->setGeometry(QRect(10, 70, 81, 22));
        origenManual->setFont(font3);
        origenAuto = new QRadioButton(ControlEmisor);
        origenAuto->setObjectName(QStringLiteral("origenAuto"));
        origenAuto->setGeometry(QRect(10, 50, 101, 22));
        origenAuto->setFont(font3);
        origenOmni = new QRadioButton(ControlEmisor);
        origenOmni->setObjectName(QStringLiteral("origenOmni"));
        origenOmni->setGeometry(QRect(10, 30, 121, 22));
        origenOmni->setFont(font3);
        startCom = new QPushButton(BarraHerramientas);
        startCom->setObjectName(QStringLiteral("startCom"));
        startCom->setGeometry(QRect(1220, 110, 61, 41));
        QFont font5;
        font5.setPointSize(10);
        startCom->setFont(font5);
        lf = new QPushButton(BarraHerramientas);
        lf->setObjectName(QStringLiteral("lf"));
        lf->setGeometry(QRect(1290, 110, 61, 41));
        lf->setFont(font5);
        btr = new QPushButton(BarraHerramientas);
        btr->setObjectName(QStringLiteral("btr"));
        btr->setGeometry(QRect(1220, 160, 61, 41));
        btr->setFont(font5);
        ppi = new QPushButton(BarraHerramientas);
        ppi->setObjectName(QStringLiteral("ppi"));
        ppi->setGeometry(QRect(1290, 160, 61, 41));
        ppi->setFont(font5);
        gan_sen = new QSpinBox(BarraHerramientas);
        gan_sen->setObjectName(QStringLiteral("gan_sen"));
        gan_sen->setGeometry(QRect(550, 160, 61, 41));
        gan_sen->setMinimum(2);
        gan_sen->setMaximum(64);
        ppi_2 = new QPushButton(BarraHerramientas);
        ppi_2->setObjectName(QStringLiteral("ppi_2"));
        ppi_2->setGeometry(QRect(30, -570, 61, 41));
        demon = new QPushButton(BarraHerramientas);
        demon->setObjectName(QStringLiteral("demon"));
        demon->setGeometry(QRect(1360, 110, 61, 41));
        demon->setFont(font5);
        label_66 = new QLabel(BarraHerramientas);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(1440, 180, 71, 20));
        frame = new QFrame(BarraHerramientas);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setGeometry(QRect(10, 10, 561, 91));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        chirpUp = new QPushButton(frame);
        chirpUp->setObjectName(QStringLiteral("chirpUp"));
        chirpUp->setGeometry(QRect(300, 40, 81, 41));
        chirpDw = new QPushButton(frame);
        chirpDw->setObjectName(QStringLiteral("chirpDw"));
        chirpDw->setGeometry(QRect(390, 40, 81, 41));
        chype = new QPushButton(frame);
        chype->setObjectName(QStringLiteral("chype"));
        chype->setGeometry(QRect(480, 40, 71, 41));
        label_68 = new QLabel(frame);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(360, 10, 181, 31));
        label_68->setFont(font4);
        label_68->setTextFormat(Qt::PlainText);
        label_68->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        chirpFrecUp = new QSpinBox(frame);
        chirpFrecUp->setObjectName(QStringLiteral("chirpFrecUp"));
        chirpFrecUp->setGeometry(QRect(200, 40, 91, 41));
        chirpFrecUp->setMinimum(7001);
        chirpFrecUp->setMaximum(15000);
        chirpFrecUp->setSingleStep(1000);
        chirpFrecUp->setValue(15000);
        label_73 = new QLabel(frame);
        label_73->setObjectName(QStringLiteral("label_73"));
        label_73->setGeometry(QRect(190, 20, 91, 20));
        label_73->setFont(font);
        label_73->setAlignment(Qt::AlignCenter);
        chirpFrecDw = new QSpinBox(frame);
        chirpFrecDw->setObjectName(QStringLiteral("chirpFrecDw"));
        chirpFrecDw->setGeometry(QRect(100, 40, 91, 41));
        chirpFrecDw->setMinimum(7000);
        chirpFrecDw->setMaximum(14999);
        chirpFrecDw->setSingleStep(1000);
        chirpFrecDw->setValue(7000);
        label_74 = new QLabel(frame);
        label_74->setObjectName(QStringLiteral("label_74"));
        label_74->setGeometry(QRect(90, 20, 91, 20));
        label_74->setFont(font);
        label_74->setAlignment(Qt::AlignCenter);
        label_75 = new QLabel(frame);
        label_75->setObjectName(QStringLiteral("label_75"));
        label_75->setGeometry(QRect(10, 16, 81, 21));
        chirpTime = new QDoubleSpinBox(frame);
        chirpTime->setObjectName(QStringLiteral("chirpTime"));
        chirpTime->setGeometry(QRect(10, 40, 81, 41));
        chirpTime->setMinimum(0.01);
        chirpTime->setMaximum(2.5);
        chirpTime->setSingleStep(0.5);
        chirpTime->setValue(1);
        water_vel = new QSpinBox(BarraHerramientas);
        water_vel->setObjectName(QStringLiteral("water_vel"));
        water_vel->setGeometry(QRect(460, 160, 81, 41));
        water_vel->setMinimum(1400);
        water_vel->setMaximum(1700);
        water_vel->setSingleStep(100);
        water_vel->setValue(1500);
        label_77 = new QLabel(BarraHerramientas);
        label_77->setObjectName(QStringLiteral("label_77"));
        label_77->setGeometry(QRect(450, 120, 91, 41));
        Ud = new QDoubleSpinBox(BarraHerramientas);
        Ud->setObjectName(QStringLiteral("Ud"));
        Ud->setGeometry(QRect(1090, 160, 101, 41));
        Ud->setMinimum(0.01);
        Ud->setMaximum(10000);
        Ud->setSingleStep(1);
        Ud->setValue(1);
        label_70 = new QLabel(BarraHerramientas);
        label_70->setObjectName(QStringLiteral("label_70"));
        label_70->setGeometry(QRect(1120, 140, 41, 17));
        QFont font6;
        font6.setPointSize(8);
        label_70->setFont(font6);
        Uu = new QDoubleSpinBox(BarraHerramientas);
        Uu->setObjectName(QStringLiteral("Uu"));
        Uu->setGeometry(QRect(1090, 100, 101, 41));
        Uu->setMinimum(0.02);
        Uu->setMaximum(9999.99);
        Uu->setValue(2);
        cleanP = new QPushButton(BarraHerramientas);
        cleanP->setObjectName(QStringLiteral("cleanP"));
        cleanP->setGeometry(QRect(1130, 60, 41, 27));
        cleanP->setFont(font6);
        prefilter = new QCheckBox(BarraHerramientas);
        prefilter->setObjectName(QStringLiteral("prefilter"));
        prefilter->setGeometry(QRect(1089, 30, 97, 22));
        prefilter->setFont(font6);
        prefilter->setChecked(true);
        cleanA = new QPushButton(BarraHerramientas);
        cleanA->setObjectName(QStringLiteral("cleanA"));
        cleanA->setGeometry(QRect(1087, 60, 41, 27));
        cleanA->setFont(font6);
        windowing = new QCheckBox(BarraHerramientas);
        windowing->setObjectName(QStringLiteral("windowing"));
        windowing->setGeometry(QRect(1089, 10, 97, 22));
        windowing->setFont(font6);
        windowing->setChecked(true);
        label_78 = new QLabel(BarraHerramientas);
        label_78->setObjectName(QStringLiteral("label_78"));
        label_78->setGeometry(QRect(620, 130, 81, 20));
        label_78->setFont(font6);
        central_frec = new QSpinBox(BarraHerramientas);
        central_frec->setObjectName(QStringLiteral("central_frec"));
        central_frec->setGeometry(QRect(620, 160, 81, 41));
        central_frec->setMinimum(10);
        central_frec->setMaximum(2500);
        central_frec->setSingleStep(10);
        central_frec->setValue(2000);
        label_79 = new QLabel(BarraHerramientas);
        label_79->setObjectName(QStringLiteral("label_79"));
        label_79->setGeometry(QRect(710, 130, 81, 20));
        label_79->setFont(font6);
        factor_p = new QDoubleSpinBox(BarraHerramientas);
        factor_p->setObjectName(QStringLiteral("factor_p"));
        factor_p->setGeometry(QRect(720, 160, 81, 41));
        factor_p->setDecimals(3);
        factor_p->setMinimum(0.1);
        factor_p->setMaximum(0.999);
        factor_p->setSingleStep(0.001);
        factor_p->setValue(0.99);
        label_72 = new QLabel(BarraHerramientas);
        label_72->setObjectName(QStringLiteral("label_72"));
        label_72->setGeometry(QRect(830, 130, 41, 20));
        label_72->setFont(font6);
        dTotal = new QSpinBox(BarraHerramientas);
        dTotal->setObjectName(QStringLiteral("dTotal"));
        dTotal->setGeometry(QRect(810, 160, 81, 41));
        dTotal->setMinimum(40);
        dTotal->setMaximum(19660);
        dTotal->setSingleStep(10);
        dTotal->setValue(200);
        label_76 = new QLabel(BarraHerramientas);
        label_76->setObjectName(QStringLiteral("label_76"));
        label_76->setGeometry(QRect(920, 130, 41, 20));
        label_76->setFont(font6);
        dPaso = new QSpinBox(BarraHerramientas);
        dPaso->setObjectName(QStringLiteral("dPaso"));
        dPaso->setGeometry(QRect(905, 160, 81, 41));
        dPaso->setMinimum(20);
        dPaso->setMaximum(307);
        dPaso->setSingleStep(10);
        dPaso->setValue(20);
        label_71 = new QLabel(BarraHerramientas);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(1000, 130, 51, 17));
        label_71->setFont(font6);
        limProm = new QSpinBox(BarraHerramientas);
        limProm->setObjectName(QStringLiteral("limProm"));
        limProm->setGeometry(QRect(1000, 160, 61, 41));
        limProm->setMinimum(2);
        limProm->setMaximum(30);
        limProm->setValue(30);
        sensor0 = new QPushButton(BarraHerramientas);
        sensor0->setObjectName(QStringLiteral("sensor0"));
        sensor0->setGeometry(QRect(1198, 56, 81, 31));
        sensor1 = new QPushButton(BarraHerramientas);
        sensor1->setObjectName(QStringLiteral("sensor1"));
        sensor1->setGeometry(QRect(1198, 15, 81, 31));
        autoSend = new QPushButton(BarraHerramientas);
        autoSend->setObjectName(QStringLiteral("autoSend"));
        autoSend->setGeometry(QRect(1360, 156, 61, 41));
        autoSend->setFont(font6);
        ControlRec->raise();
        ControlVolumen->raise();
        PulsoActivo->raise();
        edo_mar->raise();
        label_21->raise();
        prob_deteccion->raise();
        label_23->raise();
        label_24->raise();
        escala_ppi->raise();
        label_26->raise();
        dial->raise();
        ControlEmisor->raise();
        startCom->raise();
        lf->raise();
        btr->raise();
        ppi->raise();
        gan_sen->raise();
        ppi_2->raise();
        demon->raise();
        label_66->raise();
        frame->raise();
        water_vel->raise();
        label_77->raise();
        label_78->raise();
        central_frec->raise();
        Ud->raise();
        label_70->raise();
        Uu->raise();
        cleanP->raise();
        prefilter->raise();
        cleanA->raise();
        windowing->raise();
        label_78->raise();
        central_frec->raise();
        label_79->raise();
        factor_p->raise();
        label_72->raise();
        dTotal->raise();
        label_76->raise();
        dPaso->raise();
        label_71->raise();
        limProm->raise();
        sensor0->raise();
        sensor1->raise();
        autoSend->raise();
        Logos = new QFrame(centralWidget);
        Logos->setObjectName(QStringLiteral("Logos"));
        Logos->setGeometry(QRect(1300, 10, 301, 71));
        Logos->setFrameShape(QFrame::StyledPanel);
        Logos->setFrameShadow(QFrame::Raised);
        label_27 = new QLabel(Logos);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(100, 10, 121, 51));
        label_9 = new QLabel(Logos);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(6, 0, 81, 71));
        label_9->setPixmap(QPixmap(QString::fromUtf8(":/new/prefix1/resource/logo.png")));
        label_9->setScaledContents(true);
        label_10 = new QLabel(Logos);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(230, 0, 67, 71));
        label_10->setPixmap(QPixmap(QString::fromUtf8(":/new/prefix1/resource/siviso.jpg")));
        label_10->setScaledContents(true);
        PlataformaP = new QFrame(centralWidget);
        PlataformaP->setObjectName(QStringLiteral("PlataformaP"));
        PlataformaP->setGeometry(QRect(1610, 270, 301, 161));
        PlataformaP->setFrameShape(QFrame::StyledPanel);
        PlataformaP->setFrameShadow(QFrame::Raised);
        label_28 = new QLabel(PlataformaP);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(80, 10, 101, 20));
        label_29 = new QLabel(PlataformaP);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(20, 30, 67, 17));
        label_29->setFont(font6);
        label_30 = new QLabel(PlataformaP);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(20, 50, 111, 17));
        label_30->setFont(font6);
        label_31 = new QLabel(PlataformaP);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(20, 70, 67, 17));
        label_31->setFont(font6);
        label_32 = new QLabel(PlataformaP);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(20, 90, 81, 17));
        label_32->setFont(font6);
        label_33 = new QLabel(PlataformaP);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(20, 110, 71, 17));
        label_33->setFont(font6);
        label_38 = new QLabel(PlataformaP);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(160, 70, 67, 17));
        label_38->setFont(font6);
        label_39 = new QLabel(PlataformaP);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(160, 90, 67, 17));
        label_39->setFont(font6);
        label_35 = new QLabel(PlataformaP);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(20, 130, 81, 17));
        label_35->setFont(font6);
        B0Nom = new QLabel(PlataformaP);
        B0Nom->setObjectName(QStringLiteral("B0Nom"));
        B0Nom->setGeometry(QRect(90, 30, 151, 17));
        B0Nom->setFont(font5);
        B0Time = new QLabel(PlataformaP);
        B0Time->setObjectName(QStringLiteral("B0Time"));
        B0Time->setGeometry(QRect(130, 50, 151, 17));
        B0Time->setFont(font6);
        B0Lat = new QLabel(PlataformaP);
        B0Lat->setObjectName(QStringLiteral("B0Lat"));
        B0Lat->setGeometry(QRect(60, 70, 91, 20));
        B0Lat->setFont(font6);
        B0Long = new QLabel(PlataformaP);
        B0Long->setObjectName(QStringLiteral("B0Long"));
        B0Long->setGeometry(QRect(210, 70, 81, 20));
        B0Long->setFont(font6);
        B0Pr = new QLabel(PlataformaP);
        B0Pr->setObjectName(QStringLiteral("B0Pr"));
        B0Pr->setGeometry(QRect(100, 90, 61, 20));
        B0Pr->setFont(font6);
        B0Temp = new QLabel(PlataformaP);
        B0Temp->setObjectName(QStringLiteral("B0Temp"));
        B0Temp->setGeometry(QRect(230, 90, 61, 20));
        B0Temp->setFont(font6);
        B0Or = new QLabel(PlataformaP);
        B0Or->setObjectName(QStringLiteral("B0Or"));
        B0Or->setGeometry(QRect(100, 110, 61, 17));
        B0Or->setFont(font6);
        B0Carg = new QLabel(PlataformaP);
        B0Carg->setObjectName(QStringLiteral("B0Carg"));
        B0Carg->setGeometry(QRect(230, 130, 51, 20));
        B0Carg->setFont(font6);
        B0Volt = new QLabel(PlataformaP);
        B0Volt->setObjectName(QStringLiteral("B0Volt"));
        B0Volt->setGeometry(QRect(100, 130, 51, 20));
        B0Volt->setFont(font6);
        B0estado = new QLabel(PlataformaP);
        B0estado->setObjectName(QStringLiteral("B0estado"));
        B0estado->setGeometry(QRect(190, 10, 111, 20));
        B0estado->setTextFormat(Qt::PlainText);
        B0estado->setAlignment(Qt::AlignCenter);
        label_34 = new QLabel(PlataformaP);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(160, 130, 61, 17));
        label_34->setFont(font6);
        label_69 = new QLabel(PlataformaP);
        label_69->setObjectName(QStringLiteral("label_69"));
        label_69->setGeometry(QRect(160, 110, 61, 17));
        label_69->setFont(font6);
        B0Hu = new QLabel(PlataformaP);
        B0Hu->setObjectName(QStringLiteral("B0Hu"));
        B0Hu->setGeometry(QRect(230, 110, 61, 17));
        B0Hu->setFont(font6);
        CompGraf = new QFrame(centralWidget);
        CompGraf->setObjectName(QStringLiteral("CompGraf"));
        CompGraf->setGeometry(QRect(10, 310, 791, 701));
        CompGraf->setFrameShape(QFrame::StyledPanel);
        CompGraf->setFrameShadow(QFrame::Raised);
        setColorDw = new QSlider(CompGraf);
        setColorDw->setObjectName(QStringLiteral("setColorDw"));
        setColorDw->setGeometry(QRect(0, 359, 29, 331));
        setColorDw->setMaximum(254);
        setColorDw->setOrientation(Qt::Vertical);
        setColorUp = new QSlider(CompGraf);
        setColorUp->setObjectName(QStringLiteral("setColorUp"));
        setColorUp->setGeometry(QRect(0, 10, 29, 331));
        setColorUp->setMinimum(1);
        setColorUp->setMaximum(255);
        setColorUp->setValue(255);
        setColorUp->setOrientation(Qt::Vertical);
        despGraf = new QFrame(centralWidget);
        despGraf->setObjectName(QStringLiteral("despGraf"));
        despGraf->setGeometry(QRect(810, 310, 791, 701));
        despGraf->setFrameShape(QFrame::StyledPanel);
        despGraf->setFrameShadow(QFrame::Raised);
        view = new QPlainTextEdit(despGraf);
        view->setObjectName(QStringLiteral("view"));
        view->setGeometry(QRect(10, 170, 381, 481));
        textTestGrap = new QPlainTextEdit(despGraf);
        textTestGrap->setObjectName(QStringLiteral("textTestGrap"));
        textTestGrap->setGeometry(QRect(400, 170, 381, 481));
        textSend = new QLineEdit(despGraf);
        textSend->setObjectName(QStringLiteral("textSend"));
        textSend->setGeometry(QRect(402, 660, 371, 27));
        clean = new QPushButton(despGraf);
        clean->setObjectName(QStringLiteral("clean"));
        clean->setGeometry(QRect(340, 660, 51, 27));
        toolButton = new QToolButton(despGraf);
        toolButton->setObjectName(QStringLiteral("toolButton"));
        toolButton->setGeometry(QRect(10, 660, 24, 25));
        prob_falsa = new QDoubleSpinBox(despGraf);
        prob_falsa->setObjectName(QStringLiteral("prob_falsa"));
        prob_falsa->setGeometry(QRect(490, 50, 69, 41));
        endCom = new QPushButton(despGraf);
        endCom->setObjectName(QStringLiteral("endCom"));
        endCom->setGeometry(QRect(100, 46, 81, 27));
        btOpenPort = new QPushButton(despGraf);
        btOpenPort->setObjectName(QStringLiteral("btOpenPort"));
        btOpenPort->setGeometry(QRect(10, 45, 81, 27));
        GPSOr = new QPushButton(despGraf);
        GPSOr->setObjectName(QStringLiteral("GPSOr"));
        GPSOr->setGeometry(QRect(190, 10, 71, 27));
        ApagarP = new QPushButton(despGraf);
        ApagarP->setObjectName(QStringLiteral("ApagarP"));
        ApagarP->setGeometry(QRect(100, 80, 81, 27));
        radio_boya = new QDoubleSpinBox(despGraf);
        radio_boya->setObjectName(QStringLiteral("radio_boya"));
        radio_boya->setGeometry(QRect(390, 50, 69, 41));
        infoSignal = new QPushButton(despGraf);
        infoSignal->setObjectName(QStringLiteral("infoSignal"));
        infoSignal->setGeometry(QRect(100, 110, 81, 27));
        openJars = new QPushButton(despGraf);
        openJars->setObjectName(QStringLiteral("openJars"));
        openJars->setGeometry(QRect(10, 10, 81, 31));
        QFont font7;
        font7.setPointSize(12);
        openJars->setFont(font7);
        dataSim = new QPushButton(despGraf);
        dataSim->setObjectName(QStringLiteral("dataSim"));
        dataSim->setGeometry(QRect(190, 110, 81, 27));
        closeJars = new QPushButton(despGraf);
        closeJars->setObjectName(QStringLiteral("closeJars"));
        closeJars->setGeometry(QRect(100, 10, 81, 31));
        closeJars->setFont(font7);
        label_58 = new QLabel(despGraf);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(370, 4, 101, 41));
        ApagarA = new QPushButton(despGraf);
        ApagarA->setObjectName(QStringLiteral("ApagarA"));
        ApagarA->setGeometry(QRect(10, 80, 81, 27));
        save = new QPushButton(despGraf);
        save->setObjectName(QStringLiteral("save"));
        save->setGeometry(QRect(10, 110, 81, 27));
        dist = new QPushButton(despGraf);
        dist->setObjectName(QStringLiteral("dist"));
        dist->setGeometry(QRect(190, 80, 71, 27));
        prog = new QPushButton(despGraf);
        prog->setObjectName(QStringLiteral("prog"));
        prog->setGeometry(QRect(190, 50, 71, 27));
        pulso = new QPushButton(despGraf);
        pulso->setObjectName(QStringLiteral("pulso"));
        pulso->setGeometry(QRect(270, 10, 71, 27));
        label_22 = new QLabel(despGraf);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(476, 10, 91, 41));
        dt = new QDoubleSpinBox(despGraf);
        dt->setObjectName(QStringLiteral("dt"));
        dt->setGeometry(QRect(580, 120, 91, 41));
        label_8 = new QLabel(despGraf);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(388, 90, 81, 31));
        label_8->setFont(font6);
        label_11 = new QLabel(despGraf);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(486, 90, 81, 31));
        label_11->setFont(font);
        label_11->setAlignment(Qt::AlignCenter);
        label_12 = new QLabel(despGraf);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(564, 90, 121, 31));
        label_12->setFont(font);
        label_12->setAlignment(Qt::AlignCenter);
        bw = new QDoubleSpinBox(despGraf);
        bw->setObjectName(QStringLiteral("bw"));
        bw->setGeometry(QRect(380, 120, 91, 41));
        it = new QDoubleSpinBox(despGraf);
        it->setObjectName(QStringLiteral("it"));
        it->setGeometry(QRect(480, 120, 91, 41));
        escala_desp = new QDoubleSpinBox(despGraf);
        escala_desp->setObjectName(QStringLiteral("escala_desp"));
        escala_desp->setGeometry(QRect(590, 50, 69, 41));
        label_25 = new QLabel(despGraf);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(576, 6, 91, 41));
        tipo_norte = new QPushButton(despGraf);
        tipo_norte->setObjectName(QStringLiteral("tipo_norte"));
        tipo_norte->setGeometry(QRect(680, 110, 99, 51));
        tipo_norte->setFocusPolicy(Qt::WheelFocus);
        label_18 = new QLabel(despGraf);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(680, 74, 101, 41));
        ControlOrigen = new QGroupBox(despGraf);
        ControlOrigen->setObjectName(QStringLiteral("ControlOrigen"));
        ControlOrigen->setGeometry(QRect(280, 50, 81, 101));
        origenBlanco = new QRadioButton(ControlOrigen);
        origenBlanco->setObjectName(QStringLiteral("origenBlanco"));
        origenBlanco->setGeometry(QRect(10, 70, 81, 22));
        origenBlanco->setFont(font3);
        origenSensor = new QRadioButton(ControlOrigen);
        origenSensor->setObjectName(QStringLiteral("origenSensor"));
        origenSensor->setGeometry(QRect(10, 50, 81, 22));
        origenSensor->setFont(font3);
        origenBuque = new QRadioButton(ControlOrigen);
        origenBuque->setObjectName(QStringLiteral("origenBuque"));
        origenBuque->setGeometry(QRect(10, 30, 81, 22));
        origenBuque->setFont(font3);
        ang = new QSpinBox(despGraf);
        ang->setObjectName(QStringLiteral("ang"));
        ang->setGeometry(QRect(690, 20, 71, 41));
        ang->setMinimum(-179);
        ang->setMaximum(359);
        ang->setValue(0);
        view->raise();
        textTestGrap->raise();
        textSend->raise();
        clean->raise();
        label_21->raise();
        label_23->raise();
        edo_mar->raise();
        escala_ppi->raise();
        prob_deteccion->raise();
        label_24->raise();
        toolButton->raise();
        prob_falsa->raise();
        endCom->raise();
        btOpenPort->raise();
        GPSOr->raise();
        ApagarP->raise();
        radio_boya->raise();
        infoSignal->raise();
        openJars->raise();
        dataSim->raise();
        closeJars->raise();
        label_58->raise();
        ApagarA->raise();
        save->raise();
        dist->raise();
        prog->raise();
        pulso->raise();
        label_22->raise();
        dt->raise();
        label_8->raise();
        label_11->raise();
        label_12->raise();
        bw->raise();
        it->raise();
        escala_desp->raise();
        label_25->raise();
        tipo_norte->raise();
        label_18->raise();
        ControlOrigen->raise();
        ang->raise();
        MedioAmbiente = new QFrame(centralWidget);
        MedioAmbiente->setObjectName(QStringLiteral("MedioAmbiente"));
        MedioAmbiente->setGeometry(QRect(1610, 820, 301, 191));
        MedioAmbiente->setFrameShape(QFrame::StyledPanel);
        MedioAmbiente->setFrameShadow(QFrame::Raised);
        label_49 = new QLabel(MedioAmbiente);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(30, 120, 111, 17));
        label_49->setFont(font6);
        label_50 = new QLabel(MedioAmbiente);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(30, 80, 121, 17));
        label_50->setFont(font6);
        label_52 = new QLabel(MedioAmbiente);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(30, 160, 111, 17));
        label_52->setFont(font6);
        label_53 = new QLabel(MedioAmbiente);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(30, 60, 71, 17));
        label_53->setFont(font6);
        label_54 = new QLabel(MedioAmbiente);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(30, 40, 101, 17));
        label_54->setFont(font6);
        label_55 = new QLabel(MedioAmbiente);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(30, 100, 111, 17));
        label_55->setFont(font6);
        label_56 = new QLabel(MedioAmbiente);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(120, 10, 101, 20));
        label_57 = new QLabel(MedioAmbiente);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(30, 140, 101, 17));
        label_57->setFont(font6);
        dirV = new QLabel(MedioAmbiente);
        dirV->setObjectName(QStringLiteral("dirV"));
        dirV->setGeometry(QRect(140, 120, 151, 17));
        dirV->setFont(font1);
        velV = new QLabel(MedioAmbiente);
        velV->setObjectName(QStringLiteral("velV"));
        velV->setGeometry(QRect(140, 140, 151, 17));
        velV->setFont(font1);
        PlataformaActiva = new QFrame(centralWidget);
        PlataformaActiva->setObjectName(QStringLiteral("PlataformaActiva"));
        PlataformaActiva->setGeometry(QRect(1610, 100, 301, 161));
        PlataformaActiva->setFrameShape(QFrame::StyledPanel);
        PlataformaActiva->setFrameShadow(QFrame::Raised);
        label_36 = new QLabel(PlataformaActiva);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(80, 10, 101, 20));
        label_37 = new QLabel(PlataformaActiva);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(20, 30, 67, 17));
        label_37->setFont(font6);
        label_51 = new QLabel(PlataformaActiva);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(20, 43, 111, 31));
        label_51->setFont(font6);
        label_59 = new QLabel(PlataformaActiva);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(20, 70, 67, 17));
        label_59->setFont(font6);
        label_60 = new QLabel(PlataformaActiva);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(20, 90, 81, 17));
        label_60->setFont(font6);
        label_61 = new QLabel(PlataformaActiva);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(20, 110, 81, 17));
        label_61->setFont(font6);
        label_62 = new QLabel(PlataformaActiva);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(150, 130, 61, 17));
        label_62->setFont(font6);
        label_63 = new QLabel(PlataformaActiva);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(160, 70, 67, 17));
        label_63->setFont(font6);
        label_64 = new QLabel(PlataformaActiva);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(160, 90, 67, 17));
        label_64->setFont(font6);
        label_65 = new QLabel(PlataformaActiva);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(20, 130, 81, 17));
        label_65->setFont(font6);
        B1Time_2 = new QLabel(PlataformaActiva);
        B1Time_2->setObjectName(QStringLiteral("B1Time_2"));
        B1Time_2->setGeometry(QRect(80, 90, 121, 17));
        B1Time_2->setFont(font6);
        B1Lat_2 = new QLabel(PlataformaActiva);
        B1Lat_2->setObjectName(QStringLiteral("B1Lat_2"));
        B1Lat_2->setGeometry(QRect(60, 90, 91, 17));
        B1Lat_2->setFont(font6);
        B1Temp = new QLabel(PlataformaActiva);
        B1Temp->setObjectName(QStringLiteral("B1Temp"));
        B1Temp->setGeometry(QRect(230, 90, 61, 20));
        B1Temp->setFont(font6);
        B1Temp_2 = new QLabel(PlataformaActiva);
        B1Temp_2->setObjectName(QStringLiteral("B1Temp_2"));
        B1Temp_2->setGeometry(QRect(240, 170, 61, 17));
        B1Temp_2->setFont(font6);
        B1Volt_2 = new QLabel(PlataformaActiva);
        B1Volt_2->setObjectName(QStringLiteral("B1Volt_2"));
        B1Volt_2->setGeometry(QRect(250, 250, 51, 17));
        B1Volt_2->setFont(font6);
        B1Carg = new QLabel(PlataformaActiva);
        B1Carg->setObjectName(QStringLiteral("B1Carg"));
        B1Carg->setGeometry(QRect(210, 130, 51, 20));
        B1Carg->setFont(font6);
        B1Nom = new QLabel(PlataformaActiva);
        B1Nom->setObjectName(QStringLiteral("B1Nom"));
        B1Nom->setGeometry(QRect(90, 30, 151, 17));
        B1Nom->setFont(font5);
        B1Or = new QLabel(PlataformaActiva);
        B1Or->setObjectName(QStringLiteral("B1Or"));
        B1Or->setGeometry(QRect(100, 110, 61, 17));
        B1Or->setFont(font6);
        B1Volt = new QLabel(PlataformaActiva);
        B1Volt->setObjectName(QStringLiteral("B1Volt"));
        B1Volt->setGeometry(QRect(100, 130, 51, 20));
        B1Volt->setFont(font6);
        B1Lat = new QLabel(PlataformaActiva);
        B1Lat->setObjectName(QStringLiteral("B1Lat"));
        B1Lat->setGeometry(QRect(60, 70, 91, 20));
        B1Lat->setFont(font6);
        B1Pr = new QLabel(PlataformaActiva);
        B1Pr->setObjectName(QStringLiteral("B1Pr"));
        B1Pr->setGeometry(QRect(100, 90, 61, 20));
        B1Pr->setFont(font6);
        B1Long = new QLabel(PlataformaActiva);
        B1Long->setObjectName(QStringLiteral("B1Long"));
        B1Long->setGeometry(QRect(210, 70, 81, 20));
        B1Long->setFont(font6);
        B1Time = new QLabel(PlataformaActiva);
        B1Time->setObjectName(QStringLiteral("B1Time"));
        B1Time->setGeometry(QRect(130, 50, 151, 17));
        B1Time->setFont(font6);
        B1estado = new QLabel(PlataformaActiva);
        B1estado->setObjectName(QStringLiteral("B1estado"));
        B1estado->setGeometry(QRect(190, 10, 111, 20));
        B1estado->setLayoutDirection(Qt::LeftToRight);
        B1estado->setTextFormat(Qt::PlainText);
        B1estado->setAlignment(Qt::AlignCenter);
        label_67 = new QLabel(PlataformaActiva);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(160, 110, 61, 17));
        label_67->setFont(font6);
        B1Hu = new QLabel(PlataformaActiva);
        B1Hu->setObjectName(QStringLiteral("B1Hu"));
        B1Hu->setGeometry(QRect(230, 110, 61, 17));
        B1Hu->setFont(font6);
        Blancos = new QFrame(centralWidget);
        Blancos->setObjectName(QStringLiteral("Blancos"));
        Blancos->setGeometry(QRect(1610, 670, 301, 141));
        Blancos->setFrameShape(QFrame::StyledPanel);
        Blancos->setFrameShadow(QFrame::Raised);
        label_41 = new QLabel(Blancos);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(30, 50, 91, 17));
        label_41->setFont(font6);
        label_42 = new QLabel(Blancos);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(30, 110, 67, 17));
        label_42->setFont(font6);
        label_43 = new QLabel(Blancos);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(180, 110, 67, 17));
        label_43->setFont(font6);
        label_44 = new QLabel(Blancos);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(30, 30, 67, 17));
        label_44->setFont(font6);
        label_45 = new QLabel(Blancos);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(120, 10, 101, 20));
        label_47 = new QLabel(Blancos);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(30, 70, 91, 17));
        label_47->setFont(font6);
        label_48 = new QLabel(Blancos);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(30, 90, 121, 17));
        label_48->setFont(font6);
        frame_2 = new QFrame(centralWidget);
        frame_2->setObjectName(QStringLiteral("frame_2"));
        frame_2->setGeometry(QRect(1609, 439, 301, 221));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        label_90 = new QLabel(frame_2);
        label_90->setObjectName(QStringLiteral("label_90"));
        label_90->setGeometry(QRect(170, 70, 67, 17));
        label_90->setFont(font6);
        label_91 = new QLabel(frame_2);
        label_91->setObjectName(QStringLiteral("label_91"));
        label_91->setGeometry(QRect(20, 70, 67, 17));
        label_91->setFont(font6);
        label_92 = new QLabel(frame_2);
        label_92->setObjectName(QStringLiteral("label_92"));
        label_92->setGeometry(QRect(20, 130, 67, 17));
        label_92->setFont(font6);
        label_93 = new QLabel(frame_2);
        label_93->setObjectName(QStringLiteral("label_93"));
        label_93->setGeometry(QRect(20, 50, 71, 17));
        label_93->setFont(font6);
        label_94 = new QLabel(frame_2);
        label_94->setObjectName(QStringLiteral("label_94"));
        label_94->setGeometry(QRect(20, 30, 67, 17));
        label_94->setFont(font6);
        label_95 = new QLabel(frame_2);
        label_95->setObjectName(QStringLiteral("label_95"));
        label_95->setGeometry(QRect(20, 90, 111, 17));
        label_95->setFont(font6);
        label_96 = new QLabel(frame_2);
        label_96->setObjectName(QStringLiteral("label_96"));
        label_96->setGeometry(QRect(20, 170, 101, 17));
        label_96->setFont(font6);
        label_97 = new QLabel(frame_2);
        label_97->setObjectName(QStringLiteral("label_97"));
        label_97->setGeometry(QRect(110, 10, 101, 20));
        label_98 = new QLabel(frame_2);
        label_98->setObjectName(QStringLiteral("label_98"));
        label_98->setGeometry(QRect(20, 150, 91, 17));
        label_98->setFont(font6);
        ori = new QLabel(frame_2);
        ori->setObjectName(QStringLiteral("ori"));
        ori->setGeometry(QRect(130, 90, 151, 17));
        ori->setFont(font1);
        lat = new QLabel(frame_2);
        lat->setObjectName(QStringLiteral("lat"));
        lat->setGeometry(QRect(70, 70, 91, 20));
        lat->setFont(font1);
        log = new QLabel(frame_2);
        log->setObjectName(QStringLiteral("log"));
        log->setGeometry(QRect(230, 70, 61, 20));
        log->setFont(font1);
        profundidad = new QLabel(frame_2);
        profundidad->setObjectName(QStringLiteral("profundidad"));
        profundidad->setGeometry(QRect(90, 50, 201, 17));
        profundidad->setFont(font1);
        label_99 = new QLabel(frame_2);
        label_99->setObjectName(QStringLiteral("label_99"));
        label_99->setGeometry(QRect(20, 110, 67, 17));
        label_99->setFont(font6);
        vel = new QLabel(frame_2);
        vel->setObjectName(QStringLiteral("vel"));
        vel->setGeometry(QRect(90, 110, 151, 17));
        vel->setFont(font1);
        siviso->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(siviso);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1920, 25));
        siviso->setMenuBar(menuBar);
        mainToolBar = new QToolBar(siviso);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        siviso->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(siviso);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        siviso->setStatusBar(statusBar);

        retranslateUi(siviso);

        QMetaObject::connectSlotsByName(siviso);
    } // setupUi

    void retranslateUi(QMainWindow *siviso)
    {
        siviso->setWindowTitle(QApplication::translate("siviso", "siviso", 0));
        label->setText(QApplication::translate("siviso", "Alertas", 0));
        label_2->setText(QApplication::translate("siviso", "id Alerta:", 0));
        label_3->setText(QApplication::translate("siviso", "Nombre Alerta:", 0));
        label_4->setText(QApplication::translate("siviso", "Parametro de la Alerta:", 0));
        label_5->setText(QApplication::translate("siviso", "Probabilidad de falsa alarma:", 0));
        label_6->setText(QApplication::translate("siviso", "Probabilidad de detecci\303\263n:", 0));
        Alert->setText(QApplication::translate("siviso", "<html><head/><body><p><br/></p></body></html>", 0));
        rec->setText(QApplication::translate("siviso", "Grabar", 0));
        play->setText(QApplication::translate("siviso", "Reproducir", 0));
        vol_dw->setText(QApplication::translate("siviso", "-", 0));
        vol_up->setText(QApplication::translate("siviso", "+", 0));
        label_19->setText(QApplication::translate("siviso", "<html><head/><body><p align=\"center\">volumen</p></body></html>", 0));
        cw->setText(QApplication::translate("siviso", "CW", 0));
        label_13->setText(QApplication::translate("siviso", "Pulso ", 0));
        label_14->setText(QApplication::translate("siviso", "Frecuencia", 0));
        label_15->setText(QApplication::translate("siviso", "Numero de Pulsos", 0));
        label_16->setText(QApplication::translate("siviso", "<html><head/><body><p align=\"center\">Ancho del Pulso</p></body></html>", 0));
        label_17->setText(QApplication::translate("siviso", "<html><head/><body><p align=\"center\">Rango de <br/>detecci\303\263n</p></body></html>", 0));
        label_21->setText(QApplication::translate("siviso", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Estado<br/>de la mar</span></p></body></html>", 0));
        label_23->setText(QApplication::translate("siviso", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Umbral de<br/>detecci\303\263n</span></p></body></html>", 0));
        label_24->setText(QApplication::translate("siviso", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Escala<br/>PPI</span></p></body></html>", 0));
        label_26->setText(QApplication::translate("siviso", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Ganancia</span></p></body></html>", 0));
        ControlEmisor->setTitle(QApplication::translate("siviso", "Modo", 0));
        origenManual->setText(QApplication::translate("siviso", "Manual", 0));
        origenAuto->setText(QApplication::translate("siviso", "Automatico", 0));
        origenOmni->setText(QApplication::translate("siviso", "Omnidireccional", 0));
        startCom->setText(QApplication::translate("siviso", "Enlazar", 0));
        lf->setText(QApplication::translate("siviso", "LOFAR", 0));
        btr->setText(QApplication::translate("siviso", "BTR", 0));
        ppi->setText(QApplication::translate("siviso", "PPI", 0));
        ppi_2->setText(QApplication::translate("siviso", "Demon", 0));
        demon->setText(QApplication::translate("siviso", "DEMON", 0));
        label_66->setText(QApplication::translate("siviso", "Marcaci\303\263n", 0));
        chirpUp->setText(QApplication::translate("siviso", "CHIRP UP", 0));
        chirpDw->setText(QApplication::translate("siviso", "CHIRP DW", 0));
        chype->setText(QApplication::translate("siviso", "CHYPE", 0));
        label_68->setText(QApplication::translate("siviso", "Barrido de frecuencia", 0));
        label_73->setText(QApplication::translate("siviso", "Frecuencia alta", 0));
        label_74->setText(QApplication::translate("siviso", "Frecuencia baja", 0));
        label_75->setText(QApplication::translate("siviso", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Segundos</span></p></body></html>", 0));
        label_77->setText(QApplication::translate("siviso", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">velocidad <br/>del agua</span></p></body></html>", 0));
        label_70->setText(QApplication::translate("siviso", "Umbral", 0));
        cleanP->setText(QApplication::translate("siviso", "ClnP", 0));
        prefilter->setText(QApplication::translate("siviso", "prefilter", 0));
        cleanA->setText(QApplication::translate("siviso", "ClnA", 0));
        windowing->setText(QApplication::translate("siviso", "windowing", 0));
        label_78->setText(QApplication::translate("siviso", "<html><head/><body><p align=\"center\">central frec</p></body></html>", 0));
        label_79->setText(QApplication::translate("siviso", "<html><head/><body><p align=\"center\">r factor p</p></body></html>", 0));
        label_72->setText(QApplication::translate("siviso", "d total", 0));
        label_76->setText(QApplication::translate("siviso", "d paso", 0));
        label_71->setText(QApplication::translate("siviso", "LimProm", 0));
        sensor0->setText(QApplication::translate("siviso", "sensor P", 0));
        sensor1->setText(QApplication::translate("siviso", "sensor A", 0));
        autoSend->setText(QApplication::translate("siviso", "Automatico", 0));
        label_27->setText(QApplication::translate("siviso", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">SIVISO</span></p><p align=\"center\"><span style=\" font-size:8pt;\">ARMADA DE M\303\211XICO</span></p></body></html>", 0));
        label_9->setText(QString());
        label_10->setText(QString());
        label_28->setText(QApplication::translate("siviso", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Plataforma</span></p></body></html>", 0));
        label_29->setText(QApplication::translate("siviso", "Nombre:", 0));
        label_30->setText(QApplication::translate("siviso", "Tiempo de operaci\303\263n", 0));
        label_31->setText(QApplication::translate("siviso", "Latitud:", 0));
        label_32->setText(QApplication::translate("siviso", "Presion en hPa", 0));
        label_33->setText(QApplication::translate("siviso", "Orientaci\303\263n:", 0));
        label_38->setText(QApplication::translate("siviso", "Longitud:", 0));
        label_39->setText(QApplication::translate("siviso", "Temperatura", 0));
        label_35->setText(QApplication::translate("siviso", "Voltaje Bateria", 0));
        B0Nom->setText(QString());
        B0Time->setText(QString());
        B0Lat->setText(QString());
        B0Long->setText(QString());
        B0Pr->setText(QString());
        B0Temp->setText(QString());
        B0Or->setText(QString());
        B0Carg->setText(QString());
        B0Volt->setText(QString());
#ifndef QT_NO_TOOLTIP
        B0estado->setToolTip(QApplication::translate("siviso", "<html><head/><body><p align=\"center\"><br/></p></body></html>", 0));
#endif // QT_NO_TOOLTIP
        B0estado->setText(QApplication::translate("siviso", "apagado", 0));
        label_34->setText(QApplication::translate("siviso", "Porcentaje", 0));
        label_69->setText(QApplication::translate("siviso", "Humedad:", 0));
        B0Hu->setText(QString());
        clean->setText(QApplication::translate("siviso", "Cln", 0));
        toolButton->setText(QApplication::translate("siviso", "...", 0));
        endCom->setText(QApplication::translate("siviso", "fin de com", 0));
        btOpenPort->setText(QApplication::translate("siviso", "abrir puerto", 0));
        GPSOr->setText(QApplication::translate("siviso", "GPS Or", 0));
        ApagarP->setText(QApplication::translate("siviso", "Apagar P", 0));
        infoSignal->setText(QApplication::translate("siviso", "info signal", 0));
        openJars->setText(QApplication::translate("siviso", "abrir Jars", 0));
        dataSim->setText(QApplication::translate("siviso", "data simul", 0));
        closeJars->setText(QApplication::translate("siviso", "cerrar Jars", 0));
        label_58->setText(QApplication::translate("siviso", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Radio de <br/>seguridad<br/>de la Boya</span></p></body></html>", 0));
        ApagarA->setText(QApplication::translate("siviso", "Apagar A", 0));
        save->setText(QApplication::translate("siviso", "Guardar", 0));
        dist->setText(QApplication::translate("siviso", "dist", 0));
        prog->setText(QApplication::translate("siviso", "Prog", 0));
        pulso->setText(QApplication::translate("siviso", "BURST", 0));
        label_22->setText(QApplication::translate("siviso", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Probabilidad<br/>de falsa alarma</span></p></body></html>", 0));
        label_8->setText(QApplication::translate("siviso", "<html><head/><body><p align=\"center\">Ancho de <br/>Banda</p></body></html>", 0));
        label_11->setText(QApplication::translate("siviso", "<html><head/><body><p>tiempo de <br/>integraci\303\263n</p></body></html>", 0));
        label_12->setText(QApplication::translate("siviso", "<html><head/><body><p>Rango de <br/>despliegue</p></body></html>", 0));
        label_25->setText(QApplication::translate("siviso", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Escala<br/>despliegue<br/>t\303\241ctico</span></p></body></html>", 0));
        tipo_norte->setText(QApplication::translate("siviso", "Norte \n"
"Verdadero", 0));
        label_18->setText(QApplication::translate("siviso", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">alternar Norte<br/>Verdadero/Relativo </span></p></body></html>", 0));
        ControlOrigen->setTitle(QApplication::translate("siviso", "Origen", 0));
        origenBlanco->setText(QApplication::translate("siviso", "Blanco", 0));
        origenSensor->setText(QApplication::translate("siviso", "Sensor", 0));
        origenBuque->setText(QApplication::translate("siviso", "Buque", 0));
        label_49->setText(QApplication::translate("siviso", "Direcci\303\263n del viento:", 0));
        label_50->setText(QApplication::translate("siviso", "Profundidad del fondo:", 0));
        label_52->setText(QApplication::translate("siviso", "Velocidad del sonido:", 0));
        label_53->setText(QApplication::translate("siviso", "Tipo fondo:", 0));
        label_54->setText(QApplication::translate("siviso", "Salinidad del agua:", 0));
        label_55->setText(QApplication::translate("siviso", "Audio ambiente:", 0));
        label_56->setText(QApplication::translate("siviso", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Medio ambiente</span></p></body></html>", 0));
        label_57->setText(QApplication::translate("siviso", "Fuerza del viento:", 0));
        dirV->setText(QString());
        velV->setText(QString());
        label_36->setText(QApplication::translate("siviso", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Plataforma</span></p></body></html>", 0));
        label_37->setText(QApplication::translate("siviso", "Nombre:", 0));
        label_51->setText(QApplication::translate("siviso", "Tiempo de operaci\303\263n", 0));
        label_59->setText(QApplication::translate("siviso", "Latitud:", 0));
        label_60->setText(QApplication::translate("siviso", "Presion en hPa", 0));
        label_61->setText(QApplication::translate("siviso", "Orientaci\303\263n:", 0));
        label_62->setText(QApplication::translate("siviso", "Porcentaje:", 0));
        label_63->setText(QApplication::translate("siviso", "Longitud:", 0));
        label_64->setText(QApplication::translate("siviso", "Temperatura", 0));
        label_65->setText(QApplication::translate("siviso", "Voltaje Bateria", 0));
        B1Time_2->setText(QString());
        B1Lat_2->setText(QString());
        B1Temp->setText(QString());
        B1Temp_2->setText(QString());
        B1Volt_2->setText(QString());
        B1Carg->setText(QString());
        B1Nom->setText(QString());
        B1Or->setText(QString());
        B1Volt->setText(QString());
        B1Lat->setText(QString());
        B1Pr->setText(QString());
        B1Long->setText(QString());
        B1Time->setText(QString());
#ifndef QT_NO_TOOLTIP
        B1estado->setToolTip(QApplication::translate("siviso", "<html><head/><body><p align=\"center\"><br/></p></body></html>", 0));
#endif // QT_NO_TOOLTIP
        B1estado->setText(QApplication::translate("siviso", "apagado", 0));
        label_67->setText(QApplication::translate("siviso", "Humedad:", 0));
        B1Hu->setText(QString());
        label_41->setText(QApplication::translate("siviso", "Etiqueta blanco:", 0));
        label_42->setText(QApplication::translate("siviso", "Latitud:", 0));
        label_43->setText(QApplication::translate("siviso", "Longitud:", 0));
        label_44->setText(QApplication::translate("siviso", "id blanco:", 0));
        label_45->setText(QApplication::translate("siviso", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Blancos</span></p></body></html>", 0));
        label_47->setText(QApplication::translate("siviso", "Tipo blanco:", 0));
        label_48->setText(QApplication::translate("siviso", "Clasificaci\303\263n de blanco:", 0));
        label_90->setText(QApplication::translate("siviso", "Longitud:", 0));
        label_91->setText(QApplication::translate("siviso", "Latitud:", 0));
        label_92->setText(QApplication::translate("siviso", "cable usado:", 0));
        label_93->setText(QApplication::translate("siviso", "Profundidad:", 0));
        label_94->setText(QApplication::translate("siviso", "Nombre:", 0));
        label_95->setText(QApplication::translate("siviso", "Orientaci\303\263n relativa:", 0));
        label_96->setText(QApplication::translate("siviso", "tensi\303\263n del cable:", 0));
        label_97->setText(QApplication::translate("siviso", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Plataforma</span></p></body></html>", 0));
        label_98->setText(QApplication::translate("siviso", "cable disponible:", 0));
        ori->setText(QString());
        lat->setText(QString());
        log->setText(QString());
        profundidad->setText(QString());
        label_99->setText(QApplication::translate("siviso", "Velocidad:", 0));
        vel->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class siviso: public Ui_siviso {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SIVISO_H
